<!DOCTYPE html>
<html>
<body>

<h2>Error handling try&catch</h2>
<p id="demo"></p>

<script>
// function THEdivider(a, b) {
//   try {
//     if (typeof a !== "number" || typeof b !== "number") {
//       throw  Error("Both must be numbers.");
//     }
//     if (b === 0) {
//       throw  Error("Division by zero is not allowed.");
//     }
//     return a / b;
//   } catch (error) {
    
//     console.error("An error occurred:", error.message);
//     return null; 
//   }
//   finally {
//     console.log("Always show")
//   }
// }


// console.log(`First: ${THEdivider(10, 2)}`); // Output: 5
// console.log(` 2nd: ${THEdivider("five", 2)}`); //error
// console.log(` 3rd: ${THEdivider(5, 0)}`); // error






function readJSON(jsonString) {
  try {
    let data = JSON.parse(jsonString);
    return data;
  } catch (error) {
    console.error("An error occurred while parsing JSON:", error.message);
    return null; 
  }
  finally{
    console.log(`Always print`);
  }
}

// function readJSON(jsonString) {
  
//     let data = JSON.parse(jsonString);
//     return data;
// } 


let validJSON = '{"name": "X", "age": 23, "city": "Jordan"}';
let invalidJSON = '{"name": "Y", "age": 25, "city": "RUSSIA" ,}';

let validData = readJSON(validJSON);
let invalidData = readJSON(invalidJSON);

console.log(validData);   // Output: Json
console.log(`-----------`); 
console.log(`2nd ${invalidData}`); //ERROR 


</script>

</body>
</html>
